# Configuration file for Shop
# Github: http://github.com/UltrahardcoreStats/Shop

# Sets the global currency (see Bukkit's Material class)
currency: GOLD_NUGGET

# Allowed and disallowed items, add items in this way.
items:
    ENDER_PEARL:
        cost: 1
        quantity: 1
        multipleAllowed: false;